const vscode = require('vscode');
const fs = require('fs');
const path = require('path');
const os = require('os');

function activate(context) {
    // Create a native VS Code status bar item pinned to the right
    const myStatusBarItem = vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Right, 100);
    context.subscriptions.push(myStatusBarItem);

    // Locate the global hidden state folder where Claude Code records local session telemetry
    const homeDir = os.homedir();
    const claudeDir = path.join(homeDir, '.claude');

    function fetchClaudeData() {
        try {
            if (!fs.existsSync(claudeDir)) {
                myStatusBarItem.text = `🤖 Claude: Off`;
                myStatusBarItem.show();
                return;
            }

            // Find the active session file inside Claude's internal directories
            // Claude Code dumps active transcripts and session metrics inside .claude/
            const files = fs.readdirSync(claudeDir);
            
            // Look for the most recently modified session config or settings database file
            const sessionFiles = files
                .filter(f => f.endsWith('.json') || f.includes('session'))
                .map(f => ({ name: f, time: fs.statSync(path.join(claudeDir, f)).mtime.getTime() }))
                .sort((a, b) => b.time - a.time);

            if (sessionFiles.length === 0) {
                myStatusBarItem.text = `🤖 Claude: Ready`;
                myStatusBarItem.backgroundColor = undefined;
                myStatusBarItem.show();
                return;
            }

            // Read the exact JSON object recorded by Claude's core app engine
            const activeFilePath = path.join(claudeDir, sessionFiles[0].name);
            const rawContent = fs.readFileSync(activeFilePath, 'utf8').trim();
            
            if (!rawContent) return;

            const sessionData = JSON.parse(rawContent);

            // Pull direct, official numbers generated by Anthropic's platform API
            const cost = sessionData.cost?.total_cost_usd || "0.00";
            const contextPct = Math.round(sessionData.context_window?.used_percentage || 0);
            
            // Extract official token counts to derive the real cache efficiency score
            const cacheRead = sessionData.context_window?.current_usage?.cache_read_input_tokens || 0;
            const inputTokens = sessionData.context_window?.current_usage?.input_tokens || 0;
            const totalTokens = cacheRead + inputTokens;
            
            let hitRate = 100;
            if (totalTokens > 0) {
                hitRate = Math.round((cacheRead * 100) / totalTokens);
            }

            // Apply true native VS Code colors based on your strict 70/30 health boundaries
            if (hitRate >= 70) {
                myStatusBarItem.backgroundColor = new vscode.ThemeColor('statusBarItem.remoteBackground'); // Green
            } else if (hitRate <= 30) {
                myStatusBarItem.backgroundColor = new vscode.ThemeColor('statusBarItem.errorBackground'); // Red Warning
            } else {
                myStatusBarItem.backgroundColor = new vscode.ThemeColor('statusBarItem.warningBackground'); // Yellow
            }

            // Render the full, zero-approximation string directly inside the VS Code framework
            myStatusBarItem.text = `🤖 Context: ${contextPct}% | Cache: ${hitRate}% | $${parseFloat(cost).toFixed(3)}`;
            myStatusBarItem.show();

        } catch (err) {
            // Fails silently if a file is temporarily locked mid-write operation
            console.debug("Claude sync cycle locked:", err.message);
        }
    }

    // Initialize an active recursive disk observer over Claude's internal directories
    // This removes the need for terminal loops entirely
    const watcher = fs.watch(claudeDir, { recursive: true }, (eventType, filename) => {
        if (filename && (filename.endsWith('.json') || filename.includes('status'))) {
            fetchClaudeData();
        }
    });

    // Fire instantly upon booting the editor window
    fetchClaudeData();

    // Loop a background safety interval every 10 seconds to ensure consistency
    const fallbackInterval = setInterval(fetchClaudeData, 10000);

    context.subscriptions.push({
        dispose: () => {
            watcher.close();
            clearInterval(fallbackInterval);
        }
    });
}

function deactivate() {}

module.exports = { activate, deactivate };

